export * from './buildingLeft';
export * from './buildingSecLeft';
export * from './buildingPointy';
export * from './buildingRight'
export * from './cloudBottom';
export * from './cloudLeft';
export * from './cloudRight';
export * from './musicSection/progress1';
export * from './musicSection/progress2';
export * from './musicSection/track';
export * from './musicSection/pause';
export * from './musicSection/backButton';
export * from './musicSection/nexButton';
export * from './girl'
export * from './shadow'
